nome = str(input('Qual seu nome ?'))
print('Nome :', nome)
sobrenome = str(input('Seu sobrenome ?:'))
print('Sobrenome :', sobrenome)
idade = int(input('Qual sua idade :'))
print('idade :', idade)
ano_nascimento= int(input('Ano de nascimento : ?'))
print('Ano de nascimento :', ano_nascimento )
maior_de_idade = bool(idade >=18)
print('é maior de idade ?', maior_de_idade)
altura_metros = float(input('Qual sua altura ?:'))
print('Altura em metros :', altura_metros)
